intro 2

diff --git a/engine/libredwg/programs/dxf.test.in b/engine/libredwg/programs/dxf.test.in
--- a/engine/libredwg/programs/dxf.test.in
+++ b/engine/libredwg/programs/dxf.test.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # dxf.test
 #
-# Copyright (C) 2018-2023 Free Software Foundation, Inc.
+# Copyright (C) 2018-2025 Free Software Foundation, Inc.
 #
 # This program is free software, licensed under the terms of the GNU
 # General Public License as published by the Free Software Foundation,
@@ -17,6 +17,7 @@ top_builddir="@top_builddir@"
 EXEEXT="@EXEEXT@"
 DEBUG_CLASSES="@DEBUG_CLASSES@"
 TESTS_ENVIRONMENT="@AM_TESTS_ENVIRONMENT@"
+# shellcheck disable=2157
 if [ -n "$VALGRIND" ] && [ -n "$LOG_COMPILER" ]; then
     TESTPROG="$LOG_COMPILER $LOG_FLAGS"
 elif [ -n "@WINE@" ]; then
@@ -30,13 +31,57 @@ fi
 if [ -n "@HAVE_ASAN@" ]
 then
     DXF2DWG="env ASAN_OPTIONS=detect_leaks=0 $TESTPROG ./dxf2dwg${EXEEXT}"
-else    
+else
     DXF2DWG="$TESTPROG ./dxf2dwg${EXEEXT}"
+fi
+HAVE_ODA="@HAVE_ODA@"
+ODAFileConverter="@ODAFILECONVERTER@"
+if [ -n "$HAVE_ODA" ]; then
+    baseFileConverter="$(basename "$ODAFileConverter")"
 fi
 
 i=0
 rm -f ./*dxf.log
 is_release="$(grep -c 'IS_RELEASE 1' $top_builddir/src/config.h)"
+
+# ODA can only write R12+ DWG's
+convert_year_dwg() {
+    r=
+    case $year in
+        2018) r=2018 ;;
+        2013) r=2013 ;;
+        2010) r=2010 ;;
+        2007) r=2007 ;;
+        2003) r=2003 ;;
+        2000) r=2000 ;;
+        r14) r=14 ;;
+        r13) r=13 ;;
+        r12) r=12 ;;
+        r11) r=12 ;;
+        r10) r=12 ;;
+        r9) r=12 ;;
+        *) return ;;
+    esac
+}
+# ODA cannot write r11 DXF
+convert_year_dxf() {
+    r=
+    case $year in
+        2018) r=2018 ;;
+        2013) r=2013 ;;
+        2010) r=2010 ;;
+        2007) r=2007 ;;
+        2003) r=2003 ;;
+        2000) r=2000 ;;
+        r14) r=14 ;;
+        r13) r=13 ;;
+        r12) r=12 ;;
+        r11) r=12 ;;
+        r10) r=10 ;;
+        r9) r=9 ;;
+        *) return ;;
+    esac
+}
 
 check_subentity() {
     if [ -f "$dwg" ] && [ -f "$dxf" ]; then
@@ -54,6 +99,24 @@ check_subentity() {
         d="$(diff -b -U1 tmp1 tmp2)"
         test -z "$d" || echo "POLYLINE $tgt $d"
         rm tmp1 tmp2
+        if [ -n "$HAVE_ODA" ]; then
+            base="$(basename "$tgt" .dxf)"
+            rm -f "$base.dwg.err"
+            convert_year_dwg
+            # shellcheck disable=SC2086,SC2154
+            if [ -n "$r" ]; then
+                echo timeout 30 "$baseFileConverter" .. . "ACAD$r" DWG 0 1 "$base.dxf"
+                timeout 30 "$ODAFileConverter" .. . "ACAD$r" DWG 0 1 "$base.dxf" \
+                        $ODAFileConverter_geometry >/dev/null 2>/dev/null
+                if test -f "$base.dwg.err"; then
+                    cat "$base.dwg.err"
+                    echo FAIL "$baseFileConverter" "$tgt" "$year"
+                    return 1
+                fi
+            else
+                echo empty $year
+            fi
+        fi
 #   else
 #       echo skip $dxf missing
     fi
@@ -189,18 +252,47 @@ check_roundtrip() {
             exit 1
         fi
         if ! $DXF2DWG -y -v0 -o "$tgt" "$dxf" 2>/dev/null >/dev/null; then
-            echo "$DXF2DWG -y -v0 -o $tgt $dxf failed"
+            echo "$DXF2DWG -y -v0 -o $tgt $dxf failed with $?"
             exit 1
         fi
         if ! $TESTPROG "./dwgread${EXEEXT}" -v2 "$tgt" 2>"$log2" >/dev/null; then
-            echo "dwgread $tgt failed"
+            echo "dwgread $tgt failed with $?"
             exit 1
+        fi
+        # check dwg (is_dxf) with ODA, can do all versions
+        if [ -n "$HAVE_ODA" ]; then
+            rm -f "$dxf.err"
+            convert_year_dxf
+            # shellcheck disable=SC2086,SC2154
+            if [ -n "$r" ]; then
+                echo timeout 30 "$baseFileConverter" . .. "ACAD$r" DXF 0 1 "$tgt"
+                timeout 30 "$ODAFileConverter" . .. "ACAD$r" DXF 0 1 "$tgt" \
+                        $ODAFileConverter_geometry >/dev/null 2>/dev/null
+                if test -f "$dxf.err"; then
+                    cat "$dxf.err"
+                    rm -- "$dxf.err"
+                    echo FAIL "$baseFileConverter" "$tgt" "$year"
+                    i=$((i+1))
+                fi
+            else
+                echo empty $year
+            fi
         fi
         # We dont write unstable entities yet. WIPEOUT is converted to POINT in encode, but skipped at out_dxf
         if [ "$DEBUG_CLASSES" = "1" ] && [ -z "$is_release" ]; then
-            expect="$(grep -E '^Add entity' "$log1" | grep -c -v 'entity UNKNOWN_ENT')"
+            if [ "$log1" = "example_r13.log1" ]; then
+                expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (UNKNOWN_ENT|LIGHT)')"
+            else
+                expect="$(grep -E '^Add entity' "$log1" | grep -c -v 'entity UNKNOWN_ENT')"
+            fi
         else
-            expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (WIPEOUT|ARC_DIMENSION|HELIX|UNKNOWN_ENT)')"
+            if [ "$log1" = "example_r14.log1" ]; then
+                expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (WIPEOUT|ARC_DIMENSION|HELIX|UNKNOWN_ENT|LIGHT|MULTILEADER)')"
+            elif [ "$log1" = "example_r13.log1" ]; then
+                expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (WIPEOUT|ARC_DIMENSION|HELIX|UNKNOWN_ENT|LIGHT|MINSERT)')"
+            else
+                expect="$(grep -E '^Add entity' "$log1" | grep -E -c -v 'entity (WIPEOUT|ARC_DIMENSION|HELIX|UNKNOWN_ENT)')"
+            fi
         fi
         got="$(grep -E -c '^Add entity' "$log2")"
         rm "./$dxf" "./$tgt" 2>/dev/null
@@ -209,7 +301,7 @@ check_roundtrip() {
             echo "$dxf" roundtrip ok
             rm "$log1" "$log2" 2>/dev/null
         else
-            echo "$dxf" "roundtrip fail: expect $expect, got $got entities"
+            echo "$dwg" "dxf roundtrip fail: expect $expect, got $got entities"
             i=$((i+1))
             echo "expect=$expect" >"$log"
             echo "got=$got" >>"$log"
@@ -234,7 +326,7 @@ do
     check_pline_order
 done
 
-for year in 2000 2004 2007 2010 2013 2018
+for year in 2000 2004 2007 2010 2013 2018 r14 r13
 do
     base=example
     dwg="$DATADIR/${base}_${year}.dwg"
@@ -245,7 +337,8 @@ do
     check_pline_order
 done
 
-for year in 2000 2004 2007 2010 2013 2018
+# r13,r14 deleted 2 INSERT's
+for year in 2000 2004 2007 2010 2013 2018 # r14 r13
 do
     base=example
     dwg="$DATADIR/${base}_${year}.dwg"
@@ -256,8 +349,7 @@ do
     check_insert_order
 done
 
-# r14 fails on MINSERT
-for year in 2000 2004 2007 2010 2013 2018 r13 # r14
+for year in 2000 2004 2007 2010 2013 2018 r13 r14
 do
     base=example
     dwg="$DATADIR/${base}_${year}.dwg"
@@ -266,13 +358,13 @@ do
     rm "./$log" 2>/dev/null
     check_roundtrip
 done
-#for d in r11/ACEB10 r11/entities-2d r10/entities r9/entities r2.10/entities \
-#         r2.6/entities r1.4/entities
+# FIXME
+#for d in r11/ACEB10 r11/entities-2d r10/entities r9/entities r2.10/entities r2.6/entities
 #do
 #    base="$(basename $d)"
-#    year="$(dirname $d)"
+#    rel="$(dirname $d)"
 #    dwg="$DATADIR/$d.dwg"
-#    tgt="../${base}_${year}"
+#    tgt="../${base}_${rel}"
 #    log="$tgt.dxf.log"
 #    rm "./$log" 2>/dev/null
 #    check_roundtrip
